### PR TITLE
warning-free GHC 7.8.4 build

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @LukeHoersten !

First of all, thank you very much for this library!

Believe it or not but there are some projects here at work still bound to GHC 7.8.4, so I seized the chance to produce a clean, warning-free build for GHC 7.8.4 via deliberate use of `CPP` annotations. It builds using the newly-added `stack-7.8.4.yml` as well as the stock `stack.yml` one. Let me know what you think!

If you are not a fan of CPP we can always go to the CPP-free version, at the cost of some warnings in case `-Wall` is enabled (warnings coming mainly from the FTP & AMP proposals).

Alfredo

### CODE REVIEW

**Comment by LukeHoersten** [comment]
@adinapoli thanks a lot for the PR and all your hard work! I'll take a look and turn this around asap.

**Comment by adinapoli** [comment]
Thanks @LukeHoersten ! That's appreciated 😉 

Let me know if you have any feedback -- I'm very happy to amend this to meet the project's guidelines.

**Comment by LukeHoersten** [comment]
@adinapoli apologies for the delay. After discussing with my colleague, we think it may be better to go with your other suggestion of warnings but no CPP. Is that something that's easily available for PR? Thanks!

**Comment by adinapoli** [comment]
Hey Luke! Don't worry, will tackle this in the next few days. I think a collegue of mine did exactly this and there is a patch ready to land somewhere. Watch this space 😉 

Closing this PR in the meantime.

**Pull request closed without merging**
