### PR TITLE
Add Gauge.modifyAndSample function

### PR DESCRIPTION
**Pull request by shlevy**

### CODE REVIEW

**Comment by LukeHoersten** [comment]
Should we add this to more than just Guage to keep the API consistent? What's your use case for this?

**Comment by shlevy** [comment]
Sure, I can add this to the rest as well. The use case is we're developing a monitoring API (specifically an `mtl`-style typeclass) that is agnostic to backends (we want to support at least prometheus, prometheus push, and datadog). It is a lot nicer to have the class expose a `modifyGauge` function and then implement things like `add` and `sub` generically for all implementations, rather than having those special cases put into the interface implemented by the backend.

**Comment by LukeHoersten** [comment]
Makes sense. Yeah I think we should add it across all the metric types if it makes sense for completeness.

**Comment by shlevy** [comment]
@LukeHoersten Done.

**Pull request merged**
